source 'https://github.com/wuzelun/testRepos.git'

use_frameworks!


platform :ios, '8.0'

target 'testModuleA_Example' do
  pod 'testModuleA', :path => '../'
  pod "testModule", '~> 0.1.0'
  target 'testModuleA_Tests' do
    inherit! :search_paths

    
  end
end
